name: Deploy para Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy no Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy para Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

