name: Deploy to Fly.io

on:
  push:
    paths:
      - 'DeteccaoIA/**'
    branches:
      - main  # ou dev, se for seu branch principal

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: DeteccaoIA
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

